{{- if .Values.electric.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.electric.fullname" . }}
  labels:
    {{- include "project.electric.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.electric.replicaCount }}
  {{- if .Values.electric.strategy }}
  strategy:
{{ toYaml .Values.electric.strategy | indent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "project.electric.matchLabels" . | nindent 6 }}

  template:
    metadata:
    {{- if .Values.electric.podAnnotations }}
      annotations:
{{ toYaml .Values.electric.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "project.electric.labels" . | nindent 8 }}
    spec:
      initContainers:
        {{- include "supabase.database.checkdbready" .Subcharts.supabase | indent 8 }}

      containers:
      - name: electric
        image: {{ include "electric.image" . }}
        imagePullPolicy: {{ .Values.electric.image.pullPolicy }}

        ports:
        - name: satellite-http
          containerPort: {{ .Values.electric.application.listenPortSatellite }}
        - name: logical-pub-tcp
          containerPort: {{ .Values.electric.application.listenPortLogicalPub }}
        - name: pg-proxy-tcp
          containerPort: {{ .Values.electric.application.listenPortPgProxy }}
        env:
        {{- include "supabase.database.envvars" .Subcharts.supabase | indent 8 }}

        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"

        - name: LOGICAL_PUBLISHER_HOST
          value: {{ template "project.electric.fullname" . }}
        - name: LOGICAL_PUBLISHER_PORT
          value: {{ .Values.electric.application.listenPortLogicalPub | quote }}

        - name: HTTP_PORT
          value: {{ .Values.electric.application.listenPortSatellite | quote }}

        - name: PG_PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.electric.pgProxySecretName }}
              key: proxy-password

        - name: DATABASE_USE_IPV6
          value: 'false'
        - name: ELECTRIC_USE_IPV6
          value: 'false'
        - name: DATABASE_REQUIRE_SSL
          value: 'false'
        - name: AUTH_JWT_ALG
          value: {{ .Values.electric.auth.jwtAlg | quote }}

        - name: AUTH_JWT_KEY
          valueFrom:
            secretKeyRef:
            {{- if .Values.electric.auth.secretName }}
              name: {{ .Values.electric.auth.secretName }}
            {{- else }}
              name: {{ include "supabase.jwt.secretName" .Subcharts.supabase }}
            {{- end }}
            {{- if .Values.electric.auth.secretKey }}
              key: {{ .Values.electric.auth.secretKey }}
            {{- else }}
              key: {{ include "supabase.jwt.secretKey" .Subcharts.supabase }}
            {{- end }}
{{- end }}
